name: Migrations db

on: push

jobs:
  migrations:
    name: Migrations
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_AUTH_TOKEN: ${{ secrets.DATABASE_AUTH_TOKEN }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - shell: bash
        run: |
          echo "$DATABASE_URL"

      - name: pnpm install
        run: pnpm install

      - name: Run migrate file
        run: pnpm migrate
