name: Migrations db

on: push

jobs:
  migrations:
    name: Migrations
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Use Typescript
        uses: actions/typescript-action@v1

      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: Run migrate file
        run: pnpm migrate
