name: Migrations db

on: push

jobs:
  migrations:
    name: Migrations
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: pnpm install
        run: pnpm install

      - name: Run migrate file
        run: pnpm migrate
